# Generated by Django 3.0.5 on 2020-04-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_Transporte.Cargo'),
            preserve_default=False,
        ),
    ]
